# ShowCase
The following code will give you the reward dataframe

In [11]:
import numpy as np
import pandas as pd
from StochasticOptimize import MarkovDp

In [7]:
terminal_reward = np.array([2,5,10])
action_tm = np.array([[[0.5,0.3,0.2],[0.4,0.2,0.4],[0.3,0.3,0.4]],[[1,0,0],[0.4,0.3,0.3],[0.4,0.4,0.2]]])
reward = np.array([[[-1,0,1],[0,1,2],[1,2,3]],[[1,2,3],[2,3,4],[3,4,5]]])

In [8]:
dp = MarkovDp(reward,
        terminal_reward,
        action_tm)

In [9]:
df = dp.get_reward_df(2, 1)

[ 2.  5. 10.]

In [10]:
df

      n  state  action   R_n  V_n(-1)    sum  V_best  Action_best
0   0.0    0.0     0.0   2.0     0.00   2.00    2.00          0.0
1   0.0    1.0     0.0   5.0     0.00   5.00    5.00          0.0
2   0.0    2.0     0.0  10.0     0.00  10.00   10.00          0.0
3   1.0    0.0     0.0  -0.3     4.50   4.20    4.20          0.0
4   1.0    0.0     1.0   1.0     2.00   3.00    4.20          0.0
5   1.0    1.0     0.0   1.0     5.80   6.80    8.20          1.0
6   1.0    1.0     1.0   2.9     5.30   8.20    8.20          1.0
7   1.0    2.0     0.0   2.1     6.10   8.20    8.60          1.0
8   1.0    2.0     1.0   3.8     4.80   8.60    8.60          1.0
9   2.0    0.0     0.0  -0.3     6.28   5.98    5.98          0.0
10  2.0    0.0     1.0   1.0     4.20   5.20    5.98          0.0
11  2.0    1.0     0.0   1.0     6.76   7.76    9.62          1.0
12  2.0    1.0     1.0   2.9     6.72   9.62    9.62          1.0
13  2.0    2.0     0.0   2.1     7.16   9.26   10.48          1.0
14  2.0    2.0     1.0   3.8     6.68  10.48   10.48          1.0